package.json
yarn.lock

This dependency is needed if you don't have `ganache-cli` installed on your machine.
There are a lot of changes to `yarn.lock`, I think it's because other changes to `package.lock` were not followed by a `yarn install`.

Add ganache-cli dev dependency

---

.mocharc.json
test/mocha.opts
waffle.json

These Waffle and Mocha configuration files are no longer used as `buidler` configures this for us (with settings from `buidler.config.ts`).
CI - test still run and pass :tada:

Remove old waffle and mocha files

---

.solhint.json
package.json
src/contracts/GPv2Settlement.sol
test/GPv2Settlement.test.ts

This PR introduces a documented settlement contract with some really simple unit tests. I decided to make a PR right away so we can discuss the function signature of the `settle` external function.
A few things to note:
- We use `immutable` instead of storage for the `uniswapFactory`. This has the advantage that it does not perform an `SLOAD` to get the Uniswap address, but it is instead imbedded into the code at deployment :tada: 
- Currently using the global nonce per pair, which is still up for debate. (note that a pair is being uniquely identified as the `XOR` of the token addresses, ensuring that the order in which they are specified does not matter).
- Using a packed order encoding. This will require to manually decode the order. The proposed layout is included in the comments.
- …

Settlement contract

---

src/contracts/GPv2Settlement.sol
test/encoding.ts

Using `BytesLike` instead of `Bytes | string` and change `solhint-disable` to include `-next-line`.

[Easy] Two Forgotten suggestions from #224

---

bench/fixture.ts
src/contracts/libraries/GPv2Encoding.sol
src/contracts/libraries/GPv2Signing.sol
src/ts/index.ts
src/ts/order.ts
src/ts/settlement.ts
src/ts/sign.ts
test/GPv2Encoding.test.ts
test/GPv2Settlement.test.ts
test/e2e/0xTrade.test.ts
test/e2e/burnFees.test.ts
test/e2e/buyEth.test.ts
test/e2e/ercPermit.test.ts
test/e2e/orderRefunds.test.ts
test/e2e/uniswapTrade.test.ts
test/e2e/wineOilMarket.test.ts

Implements separate functions for each signature scheme used, and prepare the ground for introducing new signature schemes simply with an extra flag.
Old and new unit tests.
It looks like this PR increase the gas cost for each trade by ~275 gas.
<details><summary>comparison at f2a70c6ba5b1491e0d6ed317c647c953eda35ffe</summary>
```
=== Settlement Gas Benchmarks ===
--------------+--------------+--------------+--------------+--------------
tokens |       trades | interactions |      refunds |          gas 
--------------+--------------+--------------+--------------+--------------
2 |           10 |            0 |            0 |       747083  (change: 280 / trade)
3 |           10 |            0 |            0 |       747627  (change: 274 / trade)
4 |           10 |            0 | …
```

Separate signature schemes

---

src/contracts/GPv2AllowListAuthentication.sol
src/deploy/001_authenticator.ts
test/AllowListStorageReader.test.ts
test/GPv2AllowListAuthenticator.test.ts

Findings of a discussion with @bh2smith. This PR is not supposed to be merged nor reviewed.
The base PR #351 makes the authenticator contract upgradeable with a proxy.
This PR removes `OwnableUpgradeable` from the contract and separates the ownership of the proxy (owned by `owned`) from the ownership of the authenticator (previously called `owner`, which conflicted, now called `manager`). The "managership" of the authenticator is set as part of the proxy deployment. This makes the "proxiness" of the authenticator implicit and not explicit, since it's only evident from the deployment scripts.
The next task would be to write the authenticator contract so that it "inherits" the owner of the proxy. The function setting the manager should be restricted (maybe only called once?). Then I'd test …

[playground] Upgradeable authenticator: split proxy ownership and authenticator ownership

---

package.json
yarn.lock

This PR adds a missing `yargs` dependency that was being used in `hardhat.config.ts` (it was added in the past, but looks like it was accidentally removed at some point). It was working previously because its included as a transitive dependency and the `@types/yargs` package was installed declaring the module. However, its probably best to not depend on some package having `yargs` as a transitive dependency to work.
CI

Add missing yargs dependency

---

src/ts/deploy.ts
src/ts/index.ts
src/ts/proxy.ts
test/e2e/deployment.test.ts

(PR is part of the work in #167 to make the authenticator upgradable.)
Adds a small library to recover the implementation and the owner of EIP-1967-compatible proxies.
The two failing tests from #167 are fixed by referencing to the proxy implementation.
Next steps, in no particular order:
1. test that the address of the proxy is deterministic
2. test that the owner is the expected address, and 
3. test that the proxy upgrade process works.
Implementation retrieval is used in the existing unit tests. Owner retrieval is untested.

[upgradable authenticator] Proxy reader

---

src/ts/deploy.ts
test/e2e/deployment.test.ts

Add a unit test that verifies that the authenticator proxy is at a deterministically deployed.
It is a test!

Add test verifying deterministic deployment of proxy

---

src/contracts/mixins/GPv2Signing.sol
src/contracts/test/GPv2SigningTestInterface.sol
test/GPv2Signing.test.ts

This PR just removes some assembly that was orginally there based on the assumption that unbounded memory allocations were expensive. While this is true for large allocations, for smaller things such as abi encoding data for hashing and `ecrecover`, it isn't worth it:
<details><summary>Benchmarks</summary>
```
=== Settlement Gas Benchmarks ===
--------------+--------------+--------------+--------------+--------------
tokens |       trades | interactions |      refunds |          gas 
--------------+--------------+--------------+--------------+--------------
2 |           10 |            0 |            0 |       766307  (change: -8 / trade)
3 |           10 |            0 |            0 |       766923  (change: -3 / trade)
4 |           10 |            0 |            0 |       775879 …
```

Remove free memory pointer manipulation as has little to no effect.

---

test/GPv2Settlement.test.ts

Adds a test showing how partially filled orders cannot be settled in the fast path. As an added bonus, we reach again 100% coverage.
CI.

Test: fast path reverts if order was partially filled

---

.github/workflows/deploy.yml
.github/workflows/publish.yml

Tiny fix to the "no-op" workflows.
The `true` was changed to `'true'` because

Workflow typo

---

src/contracts/GPv2Settlement.sol
src/contracts/test/GPv2SettlementTestInterface.sol
src/deploy/002_settlement.ts
src/ts/order.ts
src/ts/settlement.ts
src/ts/swap.ts
test/GPv2Settlement.test.ts

Closes #491 
This PR implements the logic for a Balancer fast path. It is quite straight forward and will delegate most of the work to the Vault's swap interface. Specifically it configures swap limits and fund management parameters to match the signed order, preventing malicious solvers from swapping in a way that does not respect the user's limit price, or swapping for tokens that the user does not want.
Additionally, the fee transfer is specified with the swap in order to reduce the number of calls to the Vault relayer for gas efficiency.
more than 400 lines of unit tests and 100% coverage :sunglasses:. Unfortunately testing this code is quite hard because of just how many variations there are of sell/buy order x internal/external sell balance x internal/external buy balance.
This test …

Implement Balancer Fast-Path settlement logic

---

src/contracts/GPv2Settlement.sol
src/contracts/libraries/GPv2Order.sol
src/contracts/libraries/GPv2Trade.sol
src/contracts/libraries/GPv2Transfer.sol
src/contracts/test/GPv2TradeTestInterface.sol
src/deploy/002_settlement.ts
src/ts/order.ts
src/ts/settlement.ts
test/GPv2Settlement.test.ts
test/GPv2Signing.test.ts
test/GPv2Trade.test.ts
test/GPv2Transfer.test.ts
test/GPv2VaultRelayer.test.ts
test/e2e/internalBalances.test.ts
test/encoding.ts

This PR adds a new "enum" for configuring buy and sell token balances. This allows an additional value for differentiating between using ERC20 token allowance directly on the Vault relayer and external Vault balances to reuse ERC20 allowances made to the Vault using a relayer approval.
Note, that currently the SC treat `ERC20` and `EXTERNAL` the same for now, the actual differentiation will come in a follow up PR.
One thing that we should discuss is the string values for the `OrderBalance` enum, as this is what will be displayed to the user when signing the order. Looping in @anxolin 
Adjusted tests to use new enum.

New configurations for balances

---

src/contracts/libraries/GPv2Transfer.sol
src/ts/index.ts
src/ts/vault.ts
test/GPv2Settlement.test.ts
test/GPv2Transfer.test.ts
test/GPv2VaultRelayer.test.ts
test/e2e/balancerSwap.test.ts
test/e2e/internalBalances.test.ts

Closes #520, closes #535, supersedes #531 
This PR adds code to differentiate between direct ERC20 allowances to the Vault relayer and reusing Vault ERC20 allowances for settlements and the swap fast-path.
It actually turns out that having 3 sources of balances for the sell token made it easier to make these PRs slightly smaller and add incremental changes. One issue with the current implementation is that for the `swap` path with `ERC20` token balances, it currently requires **both** vault and vault relayer approvals (:vomiting_face:). This will be fixed as part of #534, and I didn't want to include it in this PR lest it gets too large.
Updated unit and e2e tests to exercise new code path, coverage should be 100%.

Differentiate between direct ERC20 and external Vault sell balances

---

src/contracts/GPv2AllowListAuthentication.sol
src/contracts/reader/AllowListStorageReader.sol
src/ts/reader.ts
test/AllowListStorageReader.test.ts
test/GPv2AllowListAuthenticator.test.ts

This PR refactors the solver allow list contract to no longer make use of the `EnumerableSet` library. The main motivations behind this change are:
- We would like to vendor our dependencies used in the Settlement contract in tree (this is to avoid package bumps leading to code changes) and this removes one 300-line dependency.
- We don't need to enumerate solvers on-chain (as we may want to enumerate them off-chain, log events were added to facilitate this).
I also took this opportunity to add doc-comments to all the methods.
Adjusted unit tests and added new ones for emitted events.

Refactor solver allow list

---

src/contracts/libraries/GPv2SafeERC20.sol
test/GPv2SafeERC20.test.ts
test/GPv2TradeExecution.test.ts

This PR adjusts our SafeERC20 library to revert on calls to non-contracts. It is optimized to only perform a check in the cases where the `transfer` returns no return data (as a non-zero return data size implies code at the address). This allows us to not incur any overhead when interacting with standards compliant ERC20 implementations :tada:  while still [conforming to Solidity calling conventions](https://docs.soliditylang.org/en/v0.7.6/control-structures.html?highlight=extcodesize#external-function-calls).
Note that this doesn't protect against mistakenly calling pre-compiles, but the risk of a user signing an order for a bad token is much lower if the address is `0x000...000n`.
Adjusted unit tests to account for new revert.
<details><summary>Benchmarks show a tiny decrease in gas …

Revert ERC20 transfers on non-contracts

---

src/contracts/GPv2UniswapRouter.sol
src/contracts/test/GPv2UniswapRouterTestInterface.sol
src/contracts/uniswap/UniswapV2Library.sol
test/GPv2UniswapRouter.test.ts

This PR just adds support for specified mock Uniswap pairs for unit tests :tada:. This will be used in a follow up PR.
N/A

Refactor Uniswap library to enable mocked pairs for unit tests

---

src/contracts/GPv2UniswapRouter.sol
src/contracts/test/GPv2UniswapRouterTestInterface.sol
src/contracts/uniswap/UniswapV2Library.sol
test/GPv2UniswapRouter.test.ts

This PR adds a method for encoding a UniswapV2Pair swap as an interaction for given input and output tokens and amount.
Added unit tests.

Add method for encoding a single Uniswap pair swap

---

src/contracts/GPv2UniswapRouter.sol
src/contracts/test/GPv2UniswapRouterTestInterface.sol
src/contracts/uniswap/UniswapV2Library.sol
test/GPv2UniswapRouter.test.ts

Closes #493 
This PR completes the GPv2 Uniswap router code allowing for use of the GPv2 for settling directly with Uniswap V2. With this settlement wrapper contract, it is possible to send a transaction with a token path and an order and have it get settled with the on-chain Uniswap price, where the trade keeps positive slippage :tada:. 
Added unit tests with mind-bending price calculations. End to end tests and benchmarks will be added in follow up PRs.

Add on-chain Uniswap price calculation

---

package.json
src/ts/sign.ts

This PR just removes the `const enum` usage. While it is nice to have stricter compiler guarantees on enum values, it makes it harder to use it with bundlers.
Also bump the package version so we can make a new release for the FE.
CI still passes.

Use regular enum

---

src/contracts/GPv2UniswapRouter.sol

https://github.com/gnosis/gp-v2-contracts/pull/558 accidentally introduced a copy-pasta error which caused the Uniswap route price to be computed twice.
This added significant gas overhead, and removing it already makes us perform better than the standard Uniswap router all the while giving positive slippage to the trader (instead of keeping it in the contract).
```
=== Uniswap Gas Benchmarks ===
--------------+--------------+--------------+--------------+--------------
hops |     strategy |   batch size |  direct swap |   batch swap 
--------------+--------------+--------------+--------------+--------------
1 |    gp router |            1 |       112096 |       195181 
1 |       router |            1 |       112096 |       199102 
...
```
CI still passes uncahnged.

Fix router copy-pasta

---

package.json

This PR just bumps the package version to alpha.17 in preparation for an npm release with #580

Bump to 0.0.1-alpha.17

---

src/ts/sign.ts
test/GPv2Signing.test.ts
test/sign.test.ts
test/testHelpers.ts

Closes #579 
As described on issue https://github.com/gnosis/gp-v2-contracts/issues/579, this change makes sure the `v` signature byte is always padded with `27`.
This is done by running the signature through [`splitSignature`/`joinSignature`](https://docs.ethers.io/v5/api/utils/bytes/#utils-splitSignature)
~Did not find out how to write a unit test for this, happy to add one if anyone know how.~
Thanks to Nick's help, I've added 2 similar unit tests. 1 for `signOrder` and one for `signOrderCancellation`
I did test it locally with CowSwap and a Ledger device. Steps:
1. Using [`yalc`](https://github.com/wclr/yalc), publish the package locally with `yalc publish`
2. On `gp-swap-ui`
1. Using the code on https://github.com/gnosis/gp-swap-ui/pull/387 locally, add the local package with `yalc …

Running signed data over ethers.utils.splitSignare/joinSignature

---

src/tasks/decode.ts
src/ts/settlement.ts
src/ts/sign.ts
test/GPv2Order.test.ts
test/decoding.test.ts
test/testHelpers.ts

Addresses [this comment](https://github.com/gnosis/gp-v2-contracts/pull/596#discussion_r615610938).
Shows the user address and order uid for every trade printed by the `decode` task. New decoding functions are added to that end.
New unit tests. Test the `decode` task. Example:
```
$ npx hardhat decode --txhash 0x2b1bda3ffcdda778e1378d4f51a9be25a4eeb149cec37e9d3464aa9b81fb9e12 --network rinkeby
```
Result:

Decode trade signer in decode task

---

package.json
src/tasks/index.ts
src/tasks/withdraw.ts

Creates a task that allows a solver to withdraw the entire token balance of the settlement contract.
It has some niceties like:
- a `--min-value` flag, which sets the minimum value necessary for a token balance to be withdrawn.
- a `--dry-run` flag to simulate the transaction without executing it.
My biggest concern with this task is that the number of tokens becomes so large that Infura starts to rate limit us. So far, this never happened in my tests, and this is the reason why the main for loop is executed synchronously.
There were many arbitrary decisions taken when choosing how to determine the USD price. I preferred to avoid using onchain prices for fear of rate limiting, so I went for 1inch mainnet and ported these values to the other networks. Do you know any nice offchain price …

Add withdraw task

---

package.json

This PR just bumps the version to `v0.1.0` in preparation for the bug bounty program.

Version bump to `0.1.0`

---

README.md
src/tasks/withdraw.ts

Fetching all traded tokens takes too long. This PR adds an optional last parameter that can be used to specify a subset of tokens to withdraw from.
Also added some instructions in the readme
Command from README

Specify token list for withdraw

---

src/contracts/GPv2Settlement.sol
src/contracts/libraries/SafeMath.sol
test/GPv2Settlement.test.ts
test/e2e/wineOilMarket.test.ts
test/testHelpers.ts

This PR fixes a minor issue where rounding was done in favour of the SC instead of being in favour of the trader for partially fillable sell orders.
In theory, if gas-price was 0, a malicious solver could take a partially fillable sell order with a low value sell token and high value buy token and fill it atom by atom to take the complete sell amount from the trader with a 0 buy amount (higher differences in price made it possible to fill more sell amount at a time while still producing 0 buy amount).
This PR addresses the issue by computing the executed buy amount with a ceiling division instead of a truncating one, rounding in favour of the trader.
Adjusted unit tests to compute exact buy amount using ceiling division, added new unit tests that verify rounding in executed amounts …

Fix rounding issue in executed amount computation

---

src/contracts/GPv2VaultRelayer.sol
src/contracts/libraries/GPv2Transfer.sol
src/contracts/test/GPv2TransferTestInterface.sol
test/GPv2Transfer.test.ts

This PR addresses a note from the SC audit that `transferFromAccount` and `transferFromAccounts` behave differently and it wasn't clear why.
This method renames the `transferFromAccount` to `fastTransferFromAccount` and adds additional function documentation to clarify the subtle difference between the two functions as well as the reason.
No logic changes, just a function rename and additional documentation - existing CI is sufficient.

Clarify single transfer differences

---

README.md

Borrowed text from #596 - to provide users with an accessible way to call on the decode script.

include instructions for settlement decoding in readme

---

src/ts/index.ts
src/ts/signers.ts
src/ts/types/ethers.ts

Closes (supersedes) https://github.com/gnosis/gp-v2-contracts/pull/650
As per comment on that PR (https://github.com/gnosis/gp-v2-contracts/pull/650#issuecomment-847916923), this change introduces a Signer class that uses `eth_signTypedData_v3` instead of `eth_signTypedData_v4` on the method `signTypedData`
Tested via `yalc` on https://github.com/gnosis/gp-swap-ui/pull/576 with TrustWallet

Added TypedDataV3Signer

---

package.json

Release `v0.0.1 alpha.18`
Version bump to release this change: https://github.com/gnosis/gp-v2-contracts/pull/659

Bump version to `0.0.1-alpha.18`

---

src/contracts/GPv2Settlement.sol
src/ts/swap.ts
test/GPv2Settlement.test.ts
test/e2e/balancerSwap.test.ts

Closes #611 
This PR allows solvers to specify tighter slippage for settling orders directly with Balancer. This would allow larger orders against Balancer to still have MEV protection as if it went through the full settlement.
The question is whether or not we want to include this in the `1.0.0` release, and do these small changes require another audit?
Added unit tests and adjusted E2E test to use solver-specified limit amounts.

Allow solvers to specify tigher slippage for Balancer fast-path

---

src/ts/deploy.ts

This PR changes the deployment salt. This is done because the authenticator storage layout changed during development, and we don't want to deal with upgrading storage of pre-release versions.

Change the salt for deployment

---

package.json
tsconfig.lib.commonjs.json
tsconfig.lib.esm.json

This PR changes the ESM build to target ES2015 for better compatibility with `create-react-app`. Additionally, typings are included in the CommonJS build (they are duplicated from the typings in the `lib/esm` directory, but it does greatly simplify using the CommonJS modules directly without increasing package size too much).
The package version was also bumped in order to prep for a new release.

Target ES2015 and duplicate typings in CommonJS build

---

package.json
tsconfig.lib.commonjs.json
tsconfig.lib.esm.json

This PR just backports #685 to the `v0.0.1` maintenance branch.

Backport #685

---

src/ts/signers.ts

Temporary fix for https://github.com/MetaMask/metamask-extension/issues/11308
This PR introduces a new wrapped signer where domain's `chainId` is transformed to an number
Using yalc, publish it locally.
On cowswap local, I'm using the new signer when the issue is detected.
Works as expected.

Added `IntChainIdTypedDataV4Signer` forcing chainId as a number

---

src/tasks/decode.ts
src/tasks/decode/interaction.ts
src/tasks/decode/interaction/erc20.ts

Adds a decoder for ERC20 interactions to the settlement decoder.
It depends on PR #715 for the definition of a decoder and how it's used.
```
$ npx hardhat decode --network mainnet --txhash 0x2e70ff6f3be7c198db8e05c5331a7ef3151303cc27da91fbd368504dec01d280
=== Tokens ===
address | index | symbol | price 
---------+-------+--------+-------
=== Trades ===
------------------------------------------------------------------------------------------------------------------------
=== Interactions ===
------------------------------------------------------------------------------------------------------------------------
--- Pre-interactions ---
┌--- Intra-interactions ---
├───  Interaction: target address 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 (erc20 token: USDC)
│     function: transfer
│ …
```

[v0.0.1] Add decoder for erc20 interactions

---

package.json
src/ts/signers.ts

This PR is a forward-port of #692 and was created by cherry-picking the merge commit:
```
$ git log -1 --pretty=oneline 23e324ffa90124090e6aed27c2547fb4977d5f4f
23e324ffa90124090e6aed27c2547fb4977d5f4f Added `IntChainIdTypedDataV4Signer` forcing chainId as a number (#692)
$ git cherry-pick 23e324ffa90124090e6aed27c2547fb4977d5f4f
Auto-merging src/ts/signers.ts
[forwardport-692 46e26d8] Added `IntChainIdTypedDataV4Signer` forcing chainId as a number (#692)
Author: Leandro Boscariol <alfetopito@users.noreply.github.com>
Date: Tue Jun 15 10:47:22 2021 -0700
1 file changed, 125 insertions(+)
```
Some additional manual fixes were also required. Specifically:
```diff
diff --git a/package.json b/package.json
index 2d5598f..688da49 100644
--- a/package.json
+++ b/package.json
@@ -26,7 +26,7 @@ …
```

Added `IntChainIdTypedDataV4Signer` forcing chainId as a number (Forward-port #692)

---

package.json

Bump the package version in order to include #768 needed in the FE.

Bump to v1.0.2

---

.github/workflows/deploy.yml

https://github.com/gnosis/gp-v2-contracts/runs/4066373645?check_suite_focus=true#step:4:207
> error @typescript-eslint/eslint-plugin@5.2.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.16.1"
error Found incompatible module.
<a href="https://gitme.me/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F93aa2734f06291524f82361ba4f72b12b053a1c5%2F68747470733a2f2f666972656261736573746f726167652e676f6f676c65617069732e636f6d2f76302f622f6769742d6d656d652d70726f642e61707073706f742e636f6d2f6f2f696d6167657325324674657374496e50726f642e6a70673f616c743d6d6564696126746f6b656e3d38303834663762632d326433342d343463312d623363632d663831343039616130353734&token=testinprod" data-gitmeme-token="testinprod"><img …

Bump node version in deploy script to fix build

---

src/tasks/dump.ts
src/ts/api.ts
test/tasks/dump.test.ts

Extracts common logic for quoting fee into a method that can be reused in the original quote as well as the requote. Will be useful when adding slippage tolerance to the withdraw script (which otherwise would also have to be copied in two places).
Unit tests still pass

Refactor fee requote

---

src/tasks/placeOrder.ts

This allows testing changes locally (e.g. for https://github.com/gnosis/gp-v2-services/pull/1460)
Use new `--app-url http://localhost:8080` param. Also check that not specifying a param still places an order on prod.

Allow place order script to point to a custom endpoint

---

src/tasks/dump.ts

When dumping a lot of tokens it can take quite some time before all approvals are mined. The current behaviour waits for one approval to be mined before issuing the next one.
This PR changes the logic to issue multiple transactions in parallel (while manually doing nonce management). This leads to much shorter runtime for the run script when using it for ~100 tokens.
Ran it a few times locally while dumping tokens today.

[Dump Script] Approve tokens without waiting for prior confirmation

---

src/tasks/dump.ts
src/tasks/withdraw.ts

This PR adds an `--origin` flag (the name was chosen to be analogous to the existing `--origin` flags in both the `dump` and `withdrawService` tasks).
This flag allows the caller of `hardhat withdraw` to specify the solver address to use for executing the withdrawal transaction from the settlement contract. Additionally, this PR also makes it possible to call the `withdraw` task for an `--origin` for which you do not have a private key. This is important to be able to build withdrawal transactions that can be sent by a Multisig solver for example.
Run the `withdraw` task for a short list of tokens so it completes quickly:
```
% npx hardhat withdraw \
--network mainnet \
--origin 0xA03be496e67Ec29bC62F01a428683D7F9c204930 \
--receiver 0x84E5c8518c248DE590D5302fD7C32d2Ae6B0123c \ …
```

Allow specifying origin parameter for withdrawals
